// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYCu-4ibDAmkJFpsArjrCktHMBiPuaUSc',
    appId: '1:96977680678:web:a675dfa039acd63f7869e7',
    messagingSenderId: '96977680678',
    projectId: 'bukku-app-2026',
    authDomain: 'bukku-app-2026.firebaseapp.com',
    storageBucket: 'bukku-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaC5TocT4ve1IDIeNwHoZdcmF3zK8843Y',
    appId: '1:96977680678:android:957ea84059dd29e17869e7',
    messagingSenderId: '96977680678',
    projectId: 'bukku-app-2026',
    storageBucket: 'bukku-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEdNSx6HG2b6ZkXZW19YMbHrmj0lWKQZU',
    appId: '1:96977680678:ios:d49388668f9f13cc7869e7',
    messagingSenderId: '96977680678',
    projectId: 'bukku-app-2026',
    storageBucket: 'bukku-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.bukku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEdNSx6HG2b6ZkXZW19YMbHrmj0lWKQZU',
    appId: '1:96977680678:ios:d49388668f9f13cc7869e7',
    messagingSenderId: '96977680678',
    projectId: 'bukku-app-2026',
    storageBucket: 'bukku-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.bukku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYCu-4ibDAmkJFpsArjrCktHMBiPuaUSc',
    appId: '1:96977680678:web:b53ad3fa215ce25a7869e7',
    messagingSenderId: '96977680678',
    projectId: 'bukku-app-2026',
    authDomain: 'bukku-app-2026.firebaseapp.com',
    storageBucket: 'bukku-app-2026.firebasestorage.app',
  );
}
